name: idlewatch_ios
description: IdleWatch Flutter app prototype
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
